//Leonardo Pereira Jorge RA: 2503689
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class FormRApartamento extends javax.swing.JFrame {
    Apartamento apartamento = new Apartamento();
    private ComandosMenu comandos = ComandosMenu.getInstanciaComandos();
    private static FormRApartamento apartamentoUnic;
    
    //Metodo Singleton
    public static FormRApartamento geraRApartamento(){
        if(apartamentoUnic == null){
            apartamentoUnic = new FormRApartamento();
        }
        return apartamentoUnic;
    }
    /**
     * Creates new form FormRApartamento
     */
    public FormRApartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bVoltar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textQtdAndares = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textAndarLoc = new javax.swing.JTextField();
        bRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textIPTU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textRua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textMetroQ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textQtdQuartos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textQtdBanheiros = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textQtdSalas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textNumeroImovel = new javax.swing.JTextField();
        textCondominioNome = new javax.swing.JTextField();
        textValorCondominio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        jLabel9.setText("Quantos andares:");

        jLabel10.setText("Andar no prédio:");

        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Registre o Apartamento preenchendo as informações abaixo:");

        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        jLabel2.setText("IPTU:");

        textIPTU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIPTUActionPerformed(evt);
            }
        });

        jLabel3.setText("Endereço:");

        jLabel4.setText("Metros quadrados:");

        jLabel5.setText("Quantidade de quartos:");

        jLabel6.setText("Quantidade de banheiros:");

        jLabel7.setText("Quantidade de salas:");

        jLabel8.setText("Número do Imóvel:");

        textCondominioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCondominioNomeActionPerformed(evt);
            }
        });

        jLabel11.setText("Nome do condomínio:");

        jLabel12.setText("Valor do condomínio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVoltar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCondominioNome)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(textAndarLoc)
                            .addComponent(jLabel10)
                            .addComponent(textValorCondominio, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(62, 62, 62))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(textMetroQ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textQtdQuartos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIPTU, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textRua, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textQtdAndares)
                                .addComponent(jLabel8)
                                .addComponent(textNumeroImovel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(textQtdSalas)
                                .addComponent(jLabel9)
                                .addComponent(textQtdBanheiros))))
                    .addContainerGap(131, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAndarLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCondominioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textValorCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVoltar)
                    .addComponent(bLimpar)
                    .addComponent(bRegistrar))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textIPTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textQtdBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textQtdSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textMetroQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNumeroImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textQtdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textQtdAndares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        voltarHome();
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        try {
            RApartamento();
            int ret = JOptionPane.showConfirmDialog(
            null,
            "Apartamento Registrado! Deseja cadastrar mais?",
            "Cadastro bem sucedido",
            JOptionPane.YES_NO_OPTION
        );
            if(ret == JOptionPane.YES_OPTION){
                limparTextos();
            } else if(ret == JOptionPane.NO_OPTION){
                dispose();
            }
        } catch (QException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Deve conter ao menos um quarto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limparTextos();
    }//GEN-LAST:event_bLimparActionPerformed

    private void textIPTUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIPTUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIPTUActionPerformed

    private void textCondominioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCondominioNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCondominioNomeActionPerformed
    
    public void RApartamento() throws QException{
        apartamento = new Apartamento();
        apartamento.setIPTU(textIPTU.getText());
        apartamento.setRua(textRua.getText());
        apartamento.setMetroQ(Float.parseFloat(textMetroQ.getText()));
        int qtdQuartos = Integer.parseInt(textQtdQuartos.getText());
        if (qtdQuartos < 1) {
            throw new QException();
        }
        apartamento.setQtdQuartos(qtdQuartos);
        apartamento.setQtdBanheiros(Integer.parseInt(textQtdBanheiros.getText()));
        apartamento.setQtdSalas(Integer.parseInt(textQtdSalas.getText()));
        apartamento.setNumero(Integer.parseInt(textNumeroImovel.getText()));
        apartamento.setAndares(Integer.parseInt(textQtdAndares.getText()));
        apartamento.setAndarLoc(Integer.parseInt(textAndarLoc.getText()));
        apartamento.setCondominioNome(textCondominioNome.getText());
        apartamento.setCondominioVal(Integer.parseInt(textValorCondominio.getText()));

        comandos.getInstanciaComandos();
        comandos.registrarApartamento(apartamento);
    }
    
    public void voltarHome(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente voltar ao menu principal?",
                "Saida",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ret == 0){
            dispose();
        }
    }
    
    public void limparTextos(){
        textIPTU.setText("");
        textRua.setText("");
        textMetroQ.setText("");
        textQtdQuartos.setText("");
        textQtdBanheiros.setText("");
        textQtdSalas.setText("");
        textNumeroImovel.setText("");
        textQtdAndares.setText("");
        textAndarLoc.setText("");
        textCondominioNome.setText("");
        textValorCondominio.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textAndarLoc;
    private javax.swing.JTextField textCondominioNome;
    private javax.swing.JTextField textIPTU;
    private javax.swing.JTextField textMetroQ;
    private javax.swing.JTextField textNumeroImovel;
    private javax.swing.JTextField textQtdAndares;
    private javax.swing.JTextField textQtdBanheiros;
    private javax.swing.JTextField textQtdQuartos;
    private javax.swing.JTextField textQtdSalas;
    private javax.swing.JTextField textRua;
    private javax.swing.JTextField textValorCondominio;
    // End of variables declaration//GEN-END:variables
}
