//Leonardo Pereira Jorge RA: 2503689
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class FormHome extends javax.swing.JFrame {
    private static FormHome homeUnic;
    
    //Metodo Singleton
    public static FormHome geraHome(){
        if(homeUnic == null){
            homeUnic = new FormHome();
        }
        return homeUnic;
    }
    /**
     * Creates new form JFormHome
     */
    public FormHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bOpcao1 = new javax.swing.JButton();
        bOpcao2 = new javax.swing.JButton();
        bOpcao3 = new javax.swing.JButton();
        bOpcao4 = new javax.swing.JButton();
        labelPrincipal = new javax.swing.JLabel();
        bOpcao5 = new javax.swing.JButton();
        bOpcao6 = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        bOpcao7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bOpcao1.setText("Registrar Casa");
        bOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcao1ActionPerformed(evt);
            }
        });

        bOpcao2.setText("Registrar Apartamento");
        bOpcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcao2ActionPerformed(evt);
            }
        });

        bOpcao3.setText("Registrar Corretor");
        bOpcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcao3ActionPerformed(evt);
            }
        });

        bOpcao4.setText("Registrar Inquilino");
        bOpcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcao4ActionPerformed(evt);
            }
        });

        labelPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPrincipal.setText("Selecione uma das opções:");

        bOpcao5.setText("Mostrar Casas");
        bOpcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcao5ActionPerformed(evt);
            }
        });

        bOpcao6.setText("Mostrar Corretores");
        bOpcao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcao6ActionPerformed(evt);
            }
        });

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        bOpcao7.setText("Mostrar Apartamentos");
        bOpcao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcao7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bOpcao6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bOpcao2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bOpcao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bOpcao3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bOpcao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bOpcao5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(bOpcao7)))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(bOpcao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOpcao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOpcao3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOpcao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOpcao5)
                    .addComponent(bOpcao7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOpcao6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOpcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcao3ActionPerformed
        abreRCorretor();
    }//GEN-LAST:event_bOpcao3ActionPerformed

    private void bOpcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcao2ActionPerformed
        abreRApartamento();
    }//GEN-LAST:event_bOpcao2ActionPerformed

    private void bOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcao1ActionPerformed
        abreRCasa();
    }//GEN-LAST:event_bOpcao1ActionPerformed

    private void bOpcao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcao6ActionPerformed
        abreTabCorretores();
    }//GEN-LAST:event_bOpcao6ActionPerformed

    private void bOpcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcao4ActionPerformed
        abreRInquilino();
    }//GEN-LAST:event_bOpcao4ActionPerformed

    private void bOpcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcao5ActionPerformed
        abreTabCasas();
    }//GEN-LAST:event_bOpcao5ActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        fechaHome();
    }//GEN-LAST:event_bSairActionPerformed

    private void bOpcao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcao7ActionPerformed
        abreTabApartamentos();
    }//GEN-LAST:event_bOpcao7ActionPerformed

    public void abreRCasa(){
       FormRCasa.geraRCasa().setVisible(true);
    }
    public void abreRApartamento(){
       FormRApartamento.geraRApartamento().setVisible(true);
    }
    public void abreRCorretor(){
       FormRCorretor.geraRCorretor().setVisible(true);
    }
    public void abreRInquilino(){
       FormRInquilino.geraRInquilino().setVisible(true);
    }
    public void abreTabCorretores(){
       FormTabCorretores.geraTabCorretores().setVisible(true);
    }
    public void abreTabCasas(){
       FormTabCasas.geraTabCasas().setVisible(true);
    }
    public void abreTabApartamentos(){
        FormTabApartamentos.geraTabApartamentos().setVisible(true);
    }
    
    public void fechaHome(){
       FormHome.geraHome().setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOpcao1;
    private javax.swing.JButton bOpcao2;
    private javax.swing.JButton bOpcao3;
    private javax.swing.JButton bOpcao4;
    private javax.swing.JButton bOpcao5;
    private javax.swing.JButton bOpcao6;
    private javax.swing.JButton bOpcao7;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel labelPrincipal;
    // End of variables declaration//GEN-END:variables
}
