//Leonardo Pereira Jorge RA: 2503689
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class FormTabApartamentos extends javax.swing.JFrame {
    private static FormTabApartamentos tabApartamentosUnic;
    private ComandosMenu comandos = ComandosMenu.getInstanciaComandos();
    private static FormTabApartamentos geraTabApartamentos;
    private ArrayList<Apartamento> apartamentos = new ArrayList<>();
    
    //Metodo Singleton
    public static FormTabApartamentos geraTabApartamentos(){
        if(tabApartamentosUnic == null){
            tabApartamentosUnic = new FormTabApartamentos();
        }
        return tabApartamentosUnic;
    }
    /**
     * Creates new form FormTabApartamentos
     */
    public FormTabApartamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableApartamentos = new javax.swing.JTable();
        bAtualizar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textIPTUEx = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Veja o relatório dos Apartamentos abaixo:");

        tableApartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IPTU", "Condominio", "Andar", "Quartos", "Banheiros", "Salas", "Andares", "m²"
            }
        ));
        jScrollPane1.setViewportView(tableApartamentos);

        bAtualizar.setText("Atualizar");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Qual IPTU deseja retirar do sistema?");

        textIPTUEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIPTUExActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textIPTUEx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIPTUEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExcluir)
                    .addComponent(bAtualizar)
                    .addComponent(bVoltar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        voltarHome();
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        popularTbApartamento();
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void textIPTUExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIPTUExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIPTUExActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        try {
            excApartamento();
            popularTbApartamento();
        } catch (IPTUException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de IPTU", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bExcluirActionPerformed

    public void popularTbApartamento(){
    DefaultTableModel modelo = (DefaultTableModel) tableApartamentos.getModel();
    modelo.setRowCount(0); 
    
    for (Apartamento apartamento : comandos.getBdApartamentos()) {
        modelo.addRow(new Object[]{apartamento.getIPTU(), apartamento.getCondominioNome(), apartamento.getAndarLoc(), apartamento.getQtdQuartos(),apartamento.getQtdBanheiros(), apartamento.getQtdSalas(), apartamento.getAndares(), apartamento.getMetroQ() });
    }
    }
    
    public void excApartamento()throws IPTUException{
        Apartamento apartamento = new Apartamento();
        String tamanhoTextIPTU = textIPTUEx.getText();
        if (tamanhoTextIPTU.length() == 0) {
            throw new IPTUException();
        }
        apartamento.setIPTU(tamanhoTextIPTU);
        apartamento = comandos.exApartamentoIPTU(apartamento);
        
        if(apartamento == null){

            JOptionPane.showMessageDialog(
                    null,
                    "Imóvel EXCLUÍDO com sucesso!",
                    "Exclusão de Imóvel",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                    null,
                    "Não existe este IPTU cadastrado!",
                    "Exclusão de Imóvel",
                    JOptionPane.ERROR_MESSAGE
            );  
        }
        textIPTUEx.setText("");
        
    }
    
    public void voltarHome(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente voltar ao menu principal?",
                "Saida",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ret == 0){
            dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableApartamentos;
    private javax.swing.JTextField textIPTUEx;
    // End of variables declaration//GEN-END:variables
}
